# Generated by Django 5.0.4 on 2024-06-24 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hate_speech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='video_title',
            field=models.CharField(max_length=255),
        ),
    ]
